# This configuration was used Ebert to review the kbaird/ticket-to-ride-backend repository
# on 590adcf7c1e2fa615e4313f1787d27f477bd4935.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://ebertapp.io/docs/config and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  remark-lint:
    enabled: true
exclude_paths:
- config
- priv/repo
- test

